### ISSUE TITLE
Link zur Klassifikation ist tot

### ISSUE THREAD

**Issue by TobiasNx** [dini-ag-kim/hochschulfaechersystematik#10]
https://github.com/dini-ag-kim/hochschulfaechersystematik/blob/ab3eecf06deef07bd474d01c7541efab0cb1690b/hochschulfaechersystematik.ttl#L10

Der Link http://bartoc.org/node/18919 schein wohl nicht mehr aktiv zu sein. Ich bin darauf über die Skohub-Vocabs Veröffentlichung gestolpert. (https://skohub.io/dini-ag-kim/hochschulfaechersystematik/heads/master/w3id.org/kim/hochschulfaechersystematik/scheme.html).

**Comment by acka47** [comment]
Ich habe gerade einen Fix in den Master gepusht: https://github.com/dini-ag-kim/hochschulfaechersystematik/commit/96614a1ede9cfcfd3c2c52b79f5c8d43ddf05540 Sollte gleich wieder gehen. Du kannst das Ticket dann gerne schließen.

**Comment by acka47** [comment]
I've also asked @nichtich to fix the redirect and he did that: http://bartoc.org/node/18919 However, we now are using the canonical URI that is shown on the page.

**Comment by acka47** [comment]
Jetzt wieder Deutsch. ;-) Der Link ist nun komischerweise anders kaputt, siehe https://w3id.org/kim/hochschulfaechersystematik/scheme. Ich sehe aber keinen Fehler im Turtle. Der Unterschied zur vorherigen Version ist, dass https genutzt wird. Seltsam.

**Comment by acka47** [comment]
Der Link funktioniert. Closing.
