### ISSUE TITLE
Neue Klassifikation 19/20 ist erschienen bzw. Versionierung

### ISSUE THREAD

**Issue by TobiasNx** [dini-ag-kim/hochschulfaechersystematik#14]
Am 21.12.2020 ist eine neue Klassifiktion erschienen. In [Bartoc](https://bartoc.org/en/node/18919) wir bereits auf die aktuelle Version verwiesen, da der Link ohne Versionsangabe ist.

Vielleicht sollte man die Listen noch einmal vergleichen. Auf Bartoc sollte eine Versionsangabe erfolgen.

 https://www.destatis.de/DE/Methoden/Klassifikationen/Bildung/studenten-pruefungsstatistik.pdf;jsessionid=D18FF57DE35AC650169B59C72F4ECA61.live721?__blob=publicationFile

**Comment by lummerland** [comment]
Wie ist denn hier das weitere Vorgehen um den aktuellen Stand hier abzubilden? Auch der destatis-Stand von 2020 (erschienen am 17.11.21) ist noch nicht hier integriert. Das Vokabular ist ja bereits produktiv im Einsatz.

**Comment by acka47** [comment]
Mit #28 erledigt. Closing.
