### ISSUE TITLE
Doppelte Konzepte

### ISSUE THREAD

**Issue by acka47** [dini-ag-kim/hochschulfaechersystematik#2]
Ich wollte gerade die URIs und Notationen an die Originalsystematik anpassen, da ist mir aufgefallen, dass die `skos:Concept`s alle doppelt in der Datei sind, siehe z.B. https://github.com/dini-ag-kim/hochschulfaechersystematik/blob/6060b10f73bfc346f72da989a19375537bd45ac4/fachgebiete.ttl#L11-L15 und https://github.com/dini-ag-kim/hochschulfaechersystematik/blob/6060b10f73bfc346f72da989a19375537bd45ac4/fachgebiete.ttl#L74-L78

Dort werden auch jeweils die `narrower`-Concepts allesamt doppelt aufgezählt. Wahrscheinlich ist es am besten, wenn du den Transformationscode anpasst, @literarymachine, damit die nur einmal auftauchen. Danach setze ich mich an die Anpassung der URIs/Notationen.

**Comment by literarymachine** [comment]
Die doppelten Einträge rühren daher, dass sie auch in der Quelldatei zweimal vorkommen. Es gibt dort zwei `valuespace`-Elemente, unter denen jeweils eine Hierarchie codiert ist:

https://github.com/dini-ag-kim/hochschulfaechersystematik/blob/master/fachgebiete.xml#L3

https://github.com/dini-ag-kim/hochschulfaechersystematik/blob/master/fachgebiete.xml#L348

@acka47 kannst du herausfinden, was es mit `valuespace property="ccm:taxonid"` vs. `valuespace property="ccm:topic"` auf sich hat?
