### ISSUE TITLE
Bioinformatik bei der Suche nach "info" nicht gefunden

### ISSUE THREAD

**Issue by TobiasNx** [dini-ag-kim/hochschulfaechersystematik#20]
ist das ein Skohub problem?

**Comment by acka47** [comment]
Kannst du konkreter werden? Wenn ich nach "bio" suche, ist es dabei:

![image](https://user-images.githubusercontent.com/160292/162141356-95f10f53-75c2-43ca-8c17-6f42cee2aea4.png)

Wahrscheinlich meinst du eine Suche nach "informatik", oder? Das würde gelöst mit https://github.com/skohub-io/skohub-vocabs/issues/153

**Comment by TobiasNx** [comment]
genau mit info finde ich das nicht.

**Comment by TobiasNx** [comment]
Hatte die Suche nach "info" nur im Titel vermerkt

**Comment by TobiasNx** [comment]
Es erschwert das Arbeiten mit einem großen Vokabular, ich habe die ganze Zeit nur gedacht, dass es 3 Kallen mit "info" im namen gibt.

**Comment by acka47** [comment]
Das geht jetzt, wenn der Index einmal neu geladen wurde:

![image](https://user-images.githubusercontent.com/160292/162207207-0ad43af2-a46d-49a5-b3ef-411bc9ad3de5.png)

**Comment by acka47** [comment]
Ich schließe das mal.
