### ISSUE TITLE
Fehlende ukrainische Labels

### ISSUE THREAD

**Issue by acka47** [dini-ag-kim/hochschulfaechersystematik#32]
Es fehlen fünf ukrainische `prefLabel`s, siehe https://skohub.io/dini-ag-kim/hochschulfaechersystematik/heads/master/w3id.org/kim/hochschulfaechersystematik/scheme.uk.html (auf "expand" klicken, dann sind die ohne ukrainisches Label rot gekennzeichnet mit "No language for "uk" provided"):

![image](https://github.com/dini-ag-kim/hochschulfaechersystematik/assets/160292/fc3369ea-db74-4aa2-a68a-ccf3b2a46c79)

**Comment by acka47** [comment]
Ich weise das mal @mirjan-hoffmann zu, der Kontakt zu einer Muttersprachlerin hat.

**Comment by mirjan-hoffmann** [comment]
Ist in Arbeit und sollte voraussichtlich nächste Woche verfügbar sein

**Comment by mirjan-hoffmann** [comment]
Die fehlenden ukrainischen Labels stehen nun via https://github.com/dini-ag-kim/hochschulfaechersystematik/pull/37 bereit.

Übersetzt von der Muttersprachlerin Nataliia Kaliuzhna
