### ISSUE TITLE
id "n302" Medienwissenschaft ist doppelt

### ISSUE THREAD

**Issue by mic-men** [dini-ag-kim/hochschulfaechersystematik#33]
Die id "n302" Medienwissenschaft ist leider doppelt.
- n1 Geisteswissenschaften › n01 Gesteswissenschaften allgemein › n302 Medienwissenschaft
- n1 Geisteswissenschaften › n19 Medienwissenschaft › n302 Medienwissenschaft

Wir sollten das schnell korrigieren. Maschinelle Verarbeitung stolpert darüber.
Wenn ich es richtig sehe, ist wohl die 2. Variante die neue (nach [https://www.destatis.de/DE/Methoden/Klassifikationen/Bildung/studenten-pruefungsstatistik.html](https://www.destatis.de/DE/Methoden/Klassifikationen/Bildung/studenten-pruefungsstatistik.html).
Der Mehrwert für die 2. Variante ergäbe sich allerdings nur, wenn hier für die Zukunft ein neuer Bereich aufgebaut werden soll. Aber vermutlich sollten wir nicht abweichen, um zukünftige Komplikationen zu vermeiden.
Wie seht ihr das?

**Comment by lummerland** [comment]
Danke für den Hinweis. Tatsächlich ist die "n302 Medienwissenschaft" schon 2020 nach "n19" verschoben worden (siehe Screenshot). Ich schau mir das mal an.
![medienwissenschaft](https://github.com/dini-ag-kim/hochschulfaechersystematik/assets/2832257/d203752d-7968-49c5-b883-dcd10b94c893)
