### ISSUE TITLE
Stabile Versionen und Workflows

### ISSUE THREAD

**Issue by mirjan-hoffmann** [dini-ag-kim/hochschulfaechersystematik#35]
Derzeit scheint es keine Versionierung der hochschulfaechersystematik zu geben und ein Commit in den stable branch stellt Anwendungen, die immer den letzten Stand dieses Branches nutzen, vor eine Herausforderung, da plötzlich breaking changes im Produktivbetrieb auftauchen können.

Zuletzt wurden mit https://github.com/dini-ag-kim/hochschulfaechersystematik/commit/f49c651b52c35e89b202626d7a9d48061a40e0eb zB einfach zwei Einträge als deprecated markiert und zusätzlich aus der Fächerhierarchie entfernt - was ein breaking change ist.

Ziel dieses Issues sollte es sein hier eine Möglichkeit zu schaffen stabile Versionen der hochschulfaechersystematik nutzen zu können. So dass nicht adhoc breaking changes eingeführt werden können, sondern etwa mit einem Major-Versionswechsel einhergehen.

**Comment by acka47** [comment]
Hallo @mirjan-hoffmann , danke, dass du das Ticket aufmachst. Wir hatten im [letzten Treffen der OER-Metadatengruppe](https://metadaten.community/t/januar-treffen-der-oer-metadatengruppe-kim-2023/138) – und ich glaube auch im Treffen davor – bereits den Umgang auf Anwendungsebene mit deprecated concepts diskutiert, siehe https://metadaten.community/t/januar-treffen-der-oer-metadatengruppe-kim-2023/138/2#wie-geht-man-mit-deprecated-skos-konzepten-um-10

Damit wir das in Zukunft berücksichtigen können, ein paar Fragen:
- Was sind denn konkret die Probleme, die du jetzt hattest?
- Was stellst du dir unter einer "stabilen Version" vor? Sollen wir GitHub Releases machen? Soll jede Version ihren eigenen Namensraum haben (was glaube ich mehr Probleme aufmachen als lösen würde)? Oder meinst du etwas ganz anderes?

**Comment by mic-men** [comment]
Die Problematik ist anscheinend, dass die "deprecated"-Einträge aus der Hierarchie losgelöst wurden, d.h.  _n241_ und _n237_ nicht mehr in den _broader_ und _narrower_ Kontext eingebettet sind.
Das scheint mir in der Tat kritisch und zu überdenken.
Im edu-sharing scheint es so zu sein, dass diese id's ignoriert werden. Das ist einerseits gut - es gibt keine Fehler und sie erscheinen nicht mehr in der Hierarchie-Liste. Andererseits ist es schlecht - die Labels erscheinen nicht mehr an den Objekten, wenn sie dort vergeben wurden. Das zumindest mein Stand der Untersuchung.
Momentan ist mein (derzeitiger) Vorschlag, dass die  _broader_ und _narrower_ Kontexte erhalten bleiben - wir das also nochmal anpassen müssten. Damit haben Systeme, die "deprecated" ignorieren, zwar zuviele/doppelte Einträge, aber es ist vorwärts und rückwärts kompatibel. Systeme müssten dann den Umgang mt "deprecated" nach eigenem Ermessen umsetzen.

**Comment by acka47** [comment]
Ich gebe @mic-men Recht. Ehrlich gesagt war mir gar nicht klar, dass die Konzepte auch aus der Hierarchie entfernt wurden. Da habe ich wohl nicht gründlich genug gereviewt.

Für SkoHub Vocabs haben wir übrigens schon den zukünftigen Umgang mit deprecated concepts recht detailliert beschrieben, siehe https://github.com/skohub-io/skohub-vocabs/issues/287

**Comment by lummerland** [comment]
[317b9fb](https://github.com/dini-ag-kim/hochschulfaechersystematik/commit/317b9fbc869a6331d60077178dbf20dd00224952) korrigiert erstmal den Fehler der entfernten Konzepte (auch wenn damit die Grundfrage noch nicht geklärt ist). Danke für den Hinweis und sorry für die Umstände!

**Comment by mic-men** [comment]
Ich meine, die _broader_-Einträge müssen auch wieder gesetzt werden - habe das mal gemacht: [c331f97](https://github.com/dini-ag-kim/hochschulfaechersystematik/commit/c331f97571eb448a271d3fe4fb12d22f8b237df5).
Bitte nochmal prüfen!

**Comment by mirjan-hoffmann** [comment]
Moin @acka47,
ja, genau, die Deprecated Einträge können durch die Änderung nicht mehr in der Hierarchie dargestellt werden. PR #36 sollte die aktuellen Probleme erstmal lösen - thx all
Dann kann jede Anwendung in Ruhe Deprecated Werte ablösen und erstmal weitermachen wie bisher ohne Zeitdruck.

Trotzdem würde ich den Gedanken der Versionierung damit noch nicht begraben. Es wäre ja auch denkbar mit einem Major-Update dann breaking changes zuzulassen und zB diese Deprecated Einträge zu entfernen. Aus meiner Sicht könnte sowas auch sehr leichtgewichtig aussehen. Ein Tag im Repo wäre für mich zB schon ausreichend. Interessant ist auch meiner Sicht ja sowieso nur das ttl-File und das liegt ja vollständig im Repo ohne das noch irgendein Artefakt oä generiert werden müsste.

**Comment by acka47** [comment]
> Ich meine, die broader-Einträge müssen auch wieder gesetzt werden

Noch ein Nachtrag zur Klarstellung: Bei `skos:broader`/`skos:narrower` reicht prinzipiell die Angabe einer Richtung, denn es handelt sich um inverse RDF Properties und die jeweils andere Richtung kann automatisch ergänzt werden. So macht es auch SkoHub Vocabs. Von daher ist es kein Fehler aber zumindest eine Inkonsistenz, weil wir ja ansonsten beides angeben. Wir könnten höchstens mal überlegen zur besseren Pflegbarkeit nur noch eine Relation in der Turtle-Datei zu haben.

**Comment by acka47** [comment]
> Trotzdem würde ich den Gedanken der Versionierung damit noch nicht begraben.

Ich mache das Ticket nochmal auf und setze es auf die [Agenda für das nächste Treffen](https://metadaten.community/t/februar-treffen-der-oer-metadatengruppe-kim/174).

**Comment by acka47** [comment]
Closing. Wir werden die Dokumetation des Vokabular-Aktualisierungsprozess mit https://github.com/dini-ag-kim/stoeberspecs/issues/9 ergänzen.
